//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testITIN22.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Benutzer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Benutzer()
        {
            this.AlleRechnungen = new HashSet<Rechnung>();
        }
    
        public int ID { get; set; }
        public int ID_Rolle { get; set; }
        public string BenutzerName { get; set; }
        public byte[] Passwort { get; set; }
        public string Vorname { get; set; }
        public string Nachname { get; set; }
        public string PLZ { get; set; }
        public string Ort { get; set; }
        public bool Aktiv { get; set; }
    
        public virtual Rolle Rolle { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rechnung> AlleRechnungen { get; set; }
    }
}
