//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testITIN22.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class RechnungsWare
    {
        public int ID { get; set; }
        public int ID_Rechnung { get; set; }
        public int ID_Ware { get; set; }
        public int Menge { get; set; }
    
        public virtual Rechnung Rechnung { get; set; }
        public virtual Ware Ware { get; set; }
    }
}
