//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testITIN22.data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbTestITIN22Entities : DbContext
    {
        public dbTestITIN22Entities()
            : base("name=dbTestITIN22Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Benutzer> AlleBenutzer { get; set; }
        public virtual DbSet<Kategorie> AlleKategorien { get; set; }
        public virtual DbSet<Rechnung> AlleRechnungen { get; set; }
        public virtual DbSet<RechnungsWare> AlleRechnungsWaren { get; set; }
        public virtual DbSet<Rolle> AlleRollen { get; set; }
        public virtual DbSet<Ware> AlleWaren { get; set; }
    }
}
